title: Hello github page
author: trannguyenhan
email: trannguyenhan01092000@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  learn github page

# social links
twitter_username: trannguyenhan # DO NOT include the @ character, or else the build will fail!
github_username:  trannguyenhan # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
